services:
  postgres:
    image: postgres:15
    container_name: postgres-keycloak
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: kc123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak-network
    ports:
      - "54321:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 5s
      timeout: 5s
      retries: 5

  keycloak:
    image: keycloak-mock:26.2
    container_name: keycloak_mock
    depends_on:
      postgres:
        condition: service_healthy
    hostname: keycloak_mock
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: kc123
      KC_HOSTNAME: localhost
      KC_HTTP_ENABLED: "true"
      KC_HTTP_PORT: 8180
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
      # KEYCLOAK_LOGLEVEL: DEBUG
      # KC_LOG_LEVEL: DEBUG
    volumes:
      - ./data:/opt/keycloak/data
      - ./data/import/realm-export.json:/opt/keycloak/data/import/realm-export.json
      - ./data/import_export:/opt/keycloak/import_export
    networks:
      - keycloak-network
    ports:
      - "8180:8180"
    # command: ["start-dev"]

networks:
  keycloak-network:
    driver: bridge

volumes:
  postgres_data:

